apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
    - name: "quality-gate"
      test_strategy: "performance"
      sequences:
        - name: "deployment"
          triggeredAfter: "10m"
              properties:
                timeframe: "5m"
          tasks:
            - name: "evaluation"
            - name: "build"
